### ISSUE TITLE
[24/12/2023 - 31/12/2023] New Models/Endpoints/Providers

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1234]
Tracking list of new models / endpoints / providers we plan on adding this week.

Comment any new models/providers/endpoints you want us to add below 👇

- [x] ollama `/api/chat` - https://github.com/BerriAI/litellm/issues/1078
- [x] ollama json mode + function calling on proxy 
- [x] openai `/chat/completions` logprobs support - https://github.com/BerriAI/litellm/issues/1194
- [x] How to user Vertex AI with proxy: https://github.com/BerriAI/litellm/issues/1232 
- [ ] Improve GCP deploy docs https://github.com/BerriAI/litellm/issues/1184
- [x] function calling support for gemini pro - https://github.com/BerriAI/litellm/issues/1214
- [x] Add cloudlfare Workers AI

**Comment by krrishdholakia** [comment]
we should pick this up for next week - https://github.com/BerriAI/litellm/issues/1184

**Comment by ghost** [comment]
tracking this as a nice to have - https://github.com/BerriAI/litellm/issues/1040 cc: @Manouchehri

**Comment by ghost** [comment]
tracking - https://github.com/BerriAI/litellm/issues/997

**Comment by ghost** [comment]
tracking - https://github.com/BerriAI/litellm/issues/1188 cc: @r1cc4rd0m4zz4

**Comment by ghost** [comment]
tracking - https://github.com/BerriAI/litellm/issues/1192

**Comment by ghost** [comment]
Adding this comment here for tracking - https://github.com/BerriAI/litellm/issues/1218#issuecomment-1869469243

There's a lot of ways we can improve our caching. cc: @Manouchehri @jeromeroussin @morgendigital let me know if y'all have any feedback on this!

**Comment by ghost** [comment]
tracking support for predibase - https://github.com/BerriAI/litellm/issues/1253

**Comment by ghost** [comment]
tracking cloudflare ai workers support here - https://github.com/BerriAI/litellm/issues/544

another user just asked for it - cc: @IvanProgramming

**Comment by ghost** [comment]
yandexgpt support requested by 2 users - https://github.com/BerriAI/litellm/issues/1254

**Comment by ghost** [comment]
Aphrodite engine endpoint - https://github.com/PygmalionAI/aphrodite-engine, https://github.com/BerriAI/litellm/pull/1153

**Comment by ghost** [comment]
Just pushed function calling support for gemini-pro on vertex ai - 
https://github.com/BerriAI/litellm/commit/86403cd14eb2247b8f4d3576e3b6f0660a67a79d

Further improvements - support it for streaming - https://github.com/BerriAI/litellm/issues/1263
