### ISSUE TITLE
[01/01/2024 - 07/01/2024] New Models/Endpoints/Providers

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1294]
Tracking list of new models / endpoints / providers we plan on adding this week.

Comment any new models/providers/endpoints you want us to add below 👇

- [ ] Predibase lorax support - https://github.com/BerriAI/litellm/issues/1253
- [ ] Deepsparse CPU inference support - https://github.com/neuralmagic/deepsparse/issues/1452
- [x] GPT-4-Vision, Gemini Pro vision cost calculation support - https://github.com/BerriAI/litellm/issues/1261, https://github.com/BerriAI/litellm/issues/1260
- [x] Support per second cost calculation (Bedrock, Replicate, etc.) - https://github.com/BerriAI/litellm/issues/1269
- [ ]  https://github.com/BerriAI/litellm/issues/1040 cc: @Manouchehri
- [ ] Gemini Pro - VertexAI function calling when streaming support - https://github.com/BerriAI/litellm/issues/1263

**Comment by ghost** [comment]
## Known Backlog: 

1. OpenMeter spend tracking support - https://github.com/BerriAI/litellm/issues/1268
2. tracking - https://github.com/BerriAI/litellm/issues/997
3. tracking - https://github.com/BerriAI/litellm/issues/1188 cc: @r1cc4rd0m4zz4
4. tracking - https://github.com/BerriAI/litellm/issues/1192
5. yandexgpt support requested by 2 users - https://github.com/BerriAI/litellm/issues/1254
6. Aphrodite engine endpoint - https://github.com/PygmalionAI/aphrodite-engine, https://github.com/BerriAI/litellm/pull/1153
7. TheBloke/NexusRaven-V2-13B-GGUF function calling support https://github.com/BerriAI/litellm/issues/1060 cc: @homanp

**Comment by ghost** [comment]
added gpt-4-turbo, turbo-vision, dall-e-2, dall-e-3 pricing for azure - https://github.com/BerriAI/litellm/commit/a9f58ec1008ed16bda49227edf43433cfe3b373a

**Comment by ghost** [comment]
tracking - https://github.com/BerriAI/litellm/issues/1303
