### ISSUE TITLE
[07/01/2024 - 14/01/2024] New Models/Endpoints/Providers/Improvements 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1362]
- [ ] Caching improvement for embedding calls - https://github.com/BerriAI/litellm/issues/1350
- [x] Rate limit awareness across routing strategies - https://github.com/BerriAI/litellm/issues/1339
- [x] Fix high-traffic timeout issue - https://github.com/BerriAI/litellm/issues/1360
- [x] Increase time window for latency based routing - https://github.com/BerriAI/litellm/issues/1361
- [x] DynamoDB support - https://github.com/BerriAI/litellm/issues/1307
- [ ] Google Secret Manager support - https://github.com/BerriAI/litellm/issues/1319
- [ ] *real* Sagemaker streaming support - https://github.com/BerriAI/litellm/issues/1384
- [x] Raise a separate exception for content violations - https://github.com/BerriAI/litellm/issues/1372
- [x] Track latency as tokens/s - https://github.com/BerriAI/litellm/issues/1393

**Comment by ghost** [comment]
## Known Backlog: 

1. OpenMeter spend tracking support - https://github.com/BerriAI/litellm/issues/1268
2. tracking - https://github.com/BerriAI/litellm/issues/997
3. tracking - https://github.com/BerriAI/litellm/issues/1188 cc: @r1cc4rd0m4zz4
4. tracking - https://github.com/BerriAI/litellm/issues/1192
5. yandexgpt support requested by 2 users - https://github.com/BerriAI/litellm/issues/1254
6. Aphrodite engine endpoint - https://github.com/PygmalionAI/aphrodite-engine, https://github.com/BerriAI/litellm/pull/1153
7. TheBloke/NexusRaven-V2-13B-GGUF function calling support https://github.com/BerriAI/litellm/issues/1060 cc: @homanp
8. Predibase lorax support - [Feature]: Add support for Predibase Lorax apis  #1253
9. Deepsparse CPU inference support - https://github.com/neuralmagic/deepsparse/issues/1452
10. Gemini Pro - VertexAI function calling when streaming support - https://github.com/BerriAI/litellm/issues/1263
11. Consistent format for model prices and context window - https://github.com/BerriAI/litellm/issues/1375

**Comment by ghost** [comment]
Initial pr for expanded time window for latency based routing made - https://github.com/BerriAI/litellm/pulls

**Comment by ghost** [comment]
Tracking - https://github.com/BerriAI/litellm/issues/1373

**Comment by ghost** [comment]
Tracking - https://github.com/BerriAI/litellm/issues/1374

**Comment by ghost** [comment]
PR for DynamoDB support made - https://github.com/BerriAI/litellm/pull/1382

Pending additional testing before merging

**Comment by ghost** [comment]
PR for bumping httpx pool limits (solves high-traffic timeout issue) - https://github.com/BerriAI/litellm/pull/1415

**Comment by ishaan-jaff** [comment]
closing
