### ISSUE TITLE
[05/02/2024 - 12/02/2024] New Models/Endpoints/Providers/Improvements

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1831]
## Spend Tracking 
- [ ]  Expose /user/delete endpoint [Feature]: Expose /user/delete endpoint  #1711
- [ ] End User Emails when a key is near its budget 
- [ ] Azure cost tracking: Set Base model on config.yaml https://github.com/BerriAI/litellm/issues/1810 
- [ ] add Region-specific amazon text embedding pricing - https://github.com/BerriAI/litellm/issues/1566
- [ ] log image count in spend logs https://github.com/BerriAI/litellm/issues/1731
- [ ] Fix spend logs cost tracking bug - https://github.com/BerriAI/litellm/issues/1806
- [ ] Batch failed spend logs calls - https://github.com/BerriAI/litellm/issues/1714
- [ ] [Feature]: Azure, OpenAI - Log Response Headers https://github.com/BerriAI/litellm/issues/1724 
- [x] Increase prisma db connection limit - https://github.com/BerriAI/litellm/issues/1714
- [ ] Control Models Based on Team ID: https://github.com/BerriAI/litellm/issues/1866
- [x] Cache key + user on create - https://github.com/BerriAI/litellm/issues/1862
- [ ] Support redis caching for user api key auth - https://github.com/BerriAI/litellm/issues/1863
- [ ] Allow setting spend logs to false - https://github.com/BerriAI/litellm/issues/1714
- [ ] batch update db cost tracking calls - https://github.com/BerriAI/litellm/issues/1867

## UI v2  
- [ ] keys without alias don’t show up - https://github.com/BerriAI/litellm/issues/1812
- [x] allow Proxy admin to set upperbounds for budgets, durations https://github.com/BerriAI/litellm/issues/1835
- [x] allow proxy admin to view and delete all keys on proxy - https://github.com/BerriAI/litellm/issues/1822
- [x] [Feature-UI]: Show users the available models for a Key - https://github.com/BerriAI/litellm/issues/1887
- [x] [Feature-UI]: Show the User ID, User Spend attributes on UI v2 https://github.com/BerriAI/litellm/issues/1695 
- [x] Have admin role defined by sub in oath token - https://github.com/BerriAI/litellm/issues/1808
- [ ] Show global spend on time-series - https://github.com/BerriAI/litellm/issues/1909
- [ ] show cost per provider (global) - https://github.com/BerriAI/litellm/issues/1911
- [ ] show keys driving spend per provider (global) - https://github.com/BerriAI/litellm/issues/1912
- [ ] show key related metadata (user email, id, etc.) - https://github.com/BerriAI/litellm/issues/1913

## Misc
- [ ] Improve proxy cold start time - https://github.com/BerriAI/litellm/issues/1769
- [x] together ai function calling support - https://github.com/BerriAI/litellm/issues/1827
- [x] fix gemini pro langfuse logging bug - https://github.com/BerriAI/litellm/issues/1811
- [x] Log llm api call failures to langfuse - https://github.com/BerriAI/litellm/issues/1820
- [ ] Gemini Pro - VertexAI function calling when streaming support - https://github.com/BerriAI/litellm/issues/1263
- [ ] Add vertex ai imagen support - https://github.com/BerriAI/litellm/issues/1707
- [ ] Setting span id on langfuse - https://github.com/BerriAI/litellm/issues/1832
- [ ] deepcopy kwargs before sending to custom callback - https://github.com/BerriAI/litellm/issues/1833
- [x] proxy shouldn't be ready if db connected but not working - https://github.com/BerriAI/litellm/issues/1814
- [ ] Enable custom ssl certificates

**Comment by ghost** [comment]
## Known Backlog: 

1. OpenMeter spend tracking support - https://github.com/BerriAI/litellm/issues/1268
2. tracking - https://github.com/BerriAI/litellm/issues/997
3. tracking - https://github.com/BerriAI/litellm/issues/1188 cc: @r1cc4rd0m4zz4
4. tracking - https://github.com/BerriAI/litellm/issues/1192
5. yandexgpt support requested by 2 users - https://github.com/BerriAI/litellm/issues/1254
6. Aphrodite engine endpoint - https://github.com/PygmalionAI/aphrodite-engine, https://github.com/BerriAI/litellm/pull/1153
7. TheBloke/NexusRaven-V2-13B-GGUF function calling support https://github.com/BerriAI/litellm/issues/1060 cc: @homanp
8. Predibase lorax support - [Feature]: Add support for Predibase Lorax apis  #1253
9. Deepsparse CPU inference support - https://github.com/neuralmagic/deepsparse/issues/1452
11. Consistent format for model prices and context window - https://github.com/BerriAI/litellm/issues/1375
12. Faster bedrock embedding calls - https://github.com/BerriAI/litellm/issues/1798
13. Add whisper support - https://github.com/BerriAI/litellm/issues/1672
