### ISSUE TITLE
[05/02/2024 - 12/02/2024] New Models/Endpoints/Providers/Improvements

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1961]
# Guardrails 
- [ ] Support llm guard - https://github.com/BerriAI/litellm/issues/1960
- [x] Support llama guard - https://github.com/BerriAI/litellm/issues/2030
- [x] Support output parsing for PII masking - https://github.com/BerriAI/litellm/issues/1967
- [x] Support turning PII masking on/off per key - https://github.com/BerriAI/litellm/issues/1990
- [ ] Support google text moderations endpoint - https://github.com/BerriAI/litellm/issues/1957
- [ ] Azure content safety integration
- [ ] Support nemo guardrails on proxy 
- [x] (perf) Run content moderation check in parallel to llm api call 
- [ ] Turn on/off PII per request - https://github.com/BerriAI/litellm/issues/2003
- [ ] AWS Content Moderation support https://github.com/BerriAI/litellm/issues/2036
- [ ] Allow custom instructions for Llama Guard - https://github.com/BerriAI/litellm/issues/2044

# Spend Tracking / Budget Management
- [ ] Allow budget manager to work with proxy https://github.com/BerriAI/litellm/issues/1976
- [x] Proxy UI - Budget failing with error 
- [x]  Admin UI - add a playground so proxy users can test / experiment with each model https://github.com/BerriAI/litellm/issues/1941
- [x] Admin UI - Add a model Info page  https://github.com/BerriAI/litellm/issues/1940
- [x]  Admin UI - When users create a key, show them their available models in a dropdown https://github.com/BerriAI/litellm/issues/1942
- [x]  Admin UI - show the available models as a dropdown when creating a new key https://github.com/BerriAI/litellm/issues/1948
- [x] [Feature]: Admin UI support generic OIDC provider configuration https://github.com/BerriAI/litellm/issues/1977
- [x] [Bug]: UI - Invalid endpoint for Key infohttps://github.com/BerriAI/litellm/issues/2002
- [x] [Bug]: chat on ui not workinghttps://github.com/BerriAI/litellm/issues/1992 
- [x] Allow tracking spend per tag - https://github.com/BerriAI/litellm/issues/1984
- [ ] Team Management Endpoints https://github.com/BerriAI/litellm/issues/1975 
- [ ] Table Names should respect standard naming: https://github.com/BerriAI/litellm/issues/1972
- [x] UI - Allow users to use chat playground : https://github.com/BerriAI/litellm/issues/1941 

# Misc
- [x] Vertex AI finish reason mapping - https://github.com/BerriAI/litellm/issues/1964
- [ ] fix router timeouts + acompletion fallbacks - https://github.com/BerriAI/litellm/issues/1959
- [ ] reuse vertex ai client (speed improvement) - https://github.com/BerriAI/litellm/issues/1938
- [ ] Cohere Aya Support - https://github.com/BerriAI/litellm/issues/1985
- [ ] Google Gemini 1.5 support - https://github.com/BerriAI/litellm/issues/1982
- [x] fix chat on ui - https://github.com/BerriAI/litellm/issues/1992
- [x] langfuse image gen logging - https://github.com/BerriAI/litellm/issues/2000
- [ ] show all teams, user is a part of in /user/info - https://github.com/BerriAI/litellm/issues/2014
- [ ] https://github.com/BerriAI/litellm/issues/1999
- [ ] Support claude on vertex ai - https://github.com/BerriAI/litellm/issues/1745
