### ISSUE TITLE
[19/02/2024 - 26/02/2024] New Models/Endpoints/Providers/Improvements

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#2056]
# Guardrails 
- [x] Support llm guard - https://github.com/BerriAI/litellm/issues/1960
- [x] #2085
- [x] #2084
- [x] #2083
- [x] #2082
- [x] #2071
- [x] #2070
- [ ] AWS Content Moderation support https://github.com/BerriAI/litellm/issues/2036
- [x] Docs for custom instructions for Llama Guard - https://github.com/BerriAI/litellm/issues/2044
- [x] #2069
- [x] #2068
- [x] #2067
- [x] #2076
- [ ] add llama guard on anyscale - https://docs.endpoints.anyscale.com/supported-models/Meta-Llama-Llama-Guard-7b/
- [x] enable ad-hoc recognizers for presidio - https://github.com/BerriAI/litellm/issues/2099
- [x] #2121
- [x] #2122
- [x] endpoints for blocking/unblocking users https://github.com/BerriAI/litellm/issues/2167
- [x] #2182

# Admin UI / Spend Tracking / Budget Management
- [x] #2181
- [x] #2185
- [x] Admin UI - allow app owners to request access to an LLM https://github.com/BerriAI/litellm/issues/2057
- [x] admin UI - for non admins the UI should show all available models and for each if the user has access to the model or no https://github.com/BerriAI/litellm/issues/2062
- [x] #2161
- [x] Admin UI SSO Keycloak https://github.com/BerriAI/litellm/issues/2130
- [x] #2162
- [x] #2136
- [x] #2137
- [x] allow users to set tpm / rpm limit when creating keys #2064 https://github.com/BerriAI/litellm/issues/2064
- [ ] Allow budget manager to work with proxy https://github.com/BerriAI/litellm/issues/1976
- [ ] Max budget not showing in UI from Azure but displays in localhost https://github.com/BerriAI/litellm/issues/2051 
- [ ] Table Names should respect standard naming: https://github.com/BerriAI/litellm/issues/1972
- [x] UI - Allow users to use chat playground : https://github.com/BerriAI/litellm/issues/1941 
- [x] #2095
- [x] #2096
- [x] #2097
- [x] #2117
- [ ] Admin UI - allow a user to add new models through the UI https://github.com/BerriAI/litellm/issues/2059
- [x] Unexpected Model Deletion in POST /key/update When Updating Team ID https://github.com/BerriAI/litellm/issues/2091
- [x] #2112
- [x] #2113
- [x] #2116
- [x] #2153
- [x] #2156
- [x] #2155
- [x] #2154
- [x] #2152
- [x] #2151

# Misc
- [ ] fix router timeouts + acompletion fallbacks - https://github.com/BerriAI/litellm/issues/1959
- [ ] reuse vertex ai client (speed improvement) - https://github.com/BerriAI/litellm/issues/1938
- [x] #2149
- [ ] Cohere Aya Support - https://github.com/BerriAI/litellm/issues/1985
- [x] Google Gemini 1.5 support - https://github.com/BerriAI/litellm/issues/1982
- [ ] Support claude on vertex ai - https://github.com/BerriAI/litellm/issues/1745
- [ ] https://github.com/BerriAI/litellm/issues/1981
- [x] https://github.com/BerriAI/litellm/issues/2074
- [x] https://github.com/BerriAI/litellm/issues/2078
- [ ] https://github.com/BerriAI/litellm/issues/2079
- [x] https://github.com/BerriAI/litellm/issues/2086
- [x] #2126
- [x] #2094
- [ ] don't log master api key to langfuse - https://github.com/BerriAI/litellm/issues/2114
- [ ] don't use http proxy for internal api's - https://github.com/BerriAI/litellm/issues/2127
