### ISSUE TITLE
[04/03/2024 - 10/03/2024] New Models/Endpoints/Providers/Improvements

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2316]
## Load Balancing 
- [ ] Support caching for /moderations - https://github.com/BerriAI/litellm/issues/2126
- [x] #2327 
- [x] #2358
- [x] #2357
- [x] #2404
- [x] #2422
- [x] #2336
- [ ] fix router timeouts + acompletion fallbacks - https://github.com/BerriAI/litellm/issues/1959
- [ ] reuse vertex ai client (speed improvement) - https://github.com/BerriAI/litellm/issues/1938
- [x] #2318
- [x] Support load balancing whisper on proxy - https://github.com/BerriAI/litellm/issues/1672
- [x] #2353
- [x] #2354
- [x] #2355
- [x] #2356
- [x] #2365
- [ ] #2372
- [x] #2381
- [ ] https://github.com/BerriAI/litellm/issues/872
- [x] #2424
- [ ] Don't retry 401 errors on router w/ num retries set

## TPM/RPM Rate Limiting
- [ ] Sync openai-compatible provider model name for completions - spend tracking https://github.com/BerriAI/litellm/issues/2079
- [x] #2370
- [ ] #2360
- [ ] #2369
- [ ] #2346
- [ ] #2359
- [ ] #2380

## Miscellaneous 

- [x] Add claude-3 support https://github.com/BerriAI/litellm/issues/2314
- [ ] #2410
- [x] https://github.com/BerriAI/litellm/issues/2397
- [x] #2361
- [x] https://github.com/BerriAI/litellm/issues/2373
- [x] https://github.com/BerriAI/litellm/issues/2383
- [ ] don't log master api key to langfuse - https://github.com/BerriAI/litellm/issues/2114
- [ ] don't use http proxy for internal api's - https://github.com/BerriAI/litellm/issues/2127
- [ ] invalidate cache for deleted keys - https://github.com/BerriAI/litellm/issues/2149
- [ ] #2317
- [x] Fix huggingface streaming error raising - https://github.com/BerriAI/litellm/issues/2180
- [ ] Merge Redis SVL PR - https://github.com/BerriAI/litellm/pull/2309 s/o @tylerhutcherson
- [ ] #2362
- [ ] #2430
- [ ] #2431
- [ ] #2429
