### ISSUE TITLE
[18/03/2024 - 25/03/2024] New Models/Endpoints/Providers/Improvements

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#2575]
# Spend Tracking 
- [x] Batch db writes 
- [ ] https://github.com/BerriAI/litellm/issues/1783
- [ ] Accurate claude 3 streaming token counting https://github.com/BerriAI/litellm/issues/2417
- [x] #2582
- [ ] cost based routing - https://github.com/BerriAI/litellm/issues/2596
- [ ] https://github.com/BerriAI/litellm/issues/2634
- [ ] https://github.com/BerriAI/litellm/issues/2633

# Load Balancing 
- [x] Datadog Integration - https://github.com/BerriAI/litellm/issues/2572
- [ ] Admin UI - team-based load balancing stats (cache hits, no. of requests, no. of errors, latency) 
- [ ] Prometheus metrics - https://github.com/BerriAI/litellm/issues/2571
- [ ] https://github.com/BerriAI/litellm/issues/2383
- [ ] https://github.com/BerriAI/litellm/issues/2332
- [ ] https://github.com/BerriAI/litellm/issues/2632

# UI QA 

- [x] P0: Users tab does not load
- [ ] P1: Create new Team does not have models in the models list
- [x] P1: Total Spend for Proxy not appearing
- [ ] P1: Users Tab does not load
- [x] P1: View Spend Reports for a key does not work
- [ ] P2: Viewing Key Table -  Table takes an extremely long width
- [ ] P2: Models - Pricing looks weird as 2e 10^-7
- [ ] P2: Model Statistics - Users mentioned it makes no sense. One model skews the graph
- [ ] P2: The settings cog on the Team UI does not work
- [x] P2: UI Pop-ups are overwhelming

# Miscellaneous 
- [x] OpenID / JWT support for admin requests 
- [x] Editable virtual keys - https://github.com/BerriAI/litellm/issues/2466
- [ ] #2576 
- [ ] https://github.com/BerriAI/litellm/pull/2400
- [x] langfuse key logging - https://github.com/BerriAI/litellm/issues/2114
- [ ] Stronger jwt tokens on ui - https://github.com/BerriAI/litellm/issues/2158
- [x] https://github.com/BerriAI/litellm/issues/2586
- [ ] https://github.com/BerriAI/litellm/issues/2608
- [ ] https://github.com/BerriAI/litellm/issues/2610
- [x] #2624
- [ ] #2625
- [ ] https://github.com/BerriAI/litellm/issues/2631
- [ ] https://github.com/BerriAI/litellm/issues/2635
- [ ] https://github.com/BerriAI/litellm/issues/872
- [ ] https://github.com/BerriAI/litellm/issues/2651

**Comment by Michelklingler** [comment]
Hi @krrishdholakia I was wondering when the feature #2586 is expected to be available in the proxy.
I rough estimate would do! Thanks!
